### ISSUE TITLE
Difficulté de transcription Recueil de pièces diverses

### ISSUE THREAD

**Issue by jnorindr** [HTR-United/CREMMA-MSS-15#4]
Bonjour,

Ayant rencontré une difficulté sur un document datant du XVe siècle dans le Recueil de pièces diverses, je me permets de vous la soumettre : 

- f. 3 : "de nostre humble demande en tant que [?] du >Roy< droit et protecteur de la chrestiennté en general"
<img width="938" alt="Capture d’écran 2022-07-14 à 18 04 54" src="https://user-images.githubusercontent.com/106514875/179028654-09dcaf78-d7d0-47a7-8f0b-c4a45776336b.png">

Merci beaucoup !

**Comment by alix-tz** [comment]
En allant chercher plu de contexte, je vois que vous avez opté pour "tuteur". C'est donc réglé ?

**Comment by jnorindr** [comment]
Oui, c'est réglé !
